name: release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

env:
  GITHUB_PUSH_TOKEN: ${{ secrets.GITHUB_PUSH_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source cide
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Setup env-vars
        run: |
          REF="${{ github.event.client_payload.ref }}"
          echo "API_VERSION=${REF#refs/*/v}" >> $GITHUB_ENV

      - name: run build script
        run: |
          npm ci
          npm run build
          zip -r dist.zip dist

      - name: archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/**

      - name: create API Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{env.GITHUB_PUSH_TOKEN}}
        with:
          tag_name: v${{env.INTERSCRIPT_VERSION}}
          release_name: Release v${{env.INTERSCRIPT_VERSION}}
          body: Auto release API v${{env.INTERSCRIPT_VERSION}} by @interscript-ci
          draft: false
          prerelease: false


      - name: upload artifact to existing release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist.zip
